server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  profiles:
    active: dev
  data:
    redis:
      host: ${spring.redis.host}
      database: ${spring.redis.database}
      port: ${spring.redis.port}
      password: ${spring.redis.password}
mybatis-plus:
  type-aliases-package: com.dp.entity # 别名扫描包
logging:
  level:
    com.dp: debug